# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 魔女
subtitle: 一位不肯放弃的程序员
description: 代码是我的圣经，程序使我快乐。&#9829; 爱编程 爱工作 &#9829;
keywords:
author: Helen Zhang
language: zh-CN
timezone:

testurl: https://github.com/HelenZhangLP/demo/blob/draft/js/Array/index.html

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://helenzhanglp.github.io/
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
# category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
auto_excerpt:
  enable: true
  length: 150
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
#external_link: false # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

tag_generator:
  path: '/tags'
  per_page: 1

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: solar

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: git@github.com:HelenZhangLP/helenzhanglp.github.io.git
  branch: master

nav:
  Home: .
  Archive: archives
  Tags: tags
  Categories: categories

# Plugins
# ~ hexo-qiniu-sync
qiniu:
  offline: false
  sync: true
  bucket: audreyzhang
  secret_file: ./qn.json # 该配置与 access_key && secret_key 取其一即可
  # access_key: 3***i
  # secret_key: s**d
  dirPrefix: static
  # 外链前缀
  urlPrefix: http://***.bkt.clouddn.com/static
  # 使用默认配置即可
  up_host: http://upload.qiniu.com
  # 本地目录
  local_dir: static
  # 是否更新已经上传过的文件(仅文件大小不同或在上次上传后进行更新的才会重新上传)
  update_exist: true
  image:
    folder: images
    extend:
  js:
    folder: js
  css:
    folder: css

codepen:
  userId: "helenzhanglp"
  theme: "0"
  default_tabs: "js,result"
  height: 500
  width: "100%"

search:
  path: search.xml
  field: post
  content: true
  format: html

sequence:
  sequence: https://bramp.github.io/js-sequence-diagrams/js/sequence-diagram-min.js
  style:
  options:
    theme:
    css_class:

tag_plantuml:
  type: static