nav:
  Home: /
  About: /about/
  Writing: /archives/
  Tags: /tags/
  Projects: https://github.com/HelenZhangLP

projects_url: https://github.com/HelenZhangLP

customize:
    gravatar:
        email: 
    logo:
        enabled: true
        width: 50
        height: 50
        url: /images/logo.jpeg
        gravatar: false
    favicon: 
      # eg. generate with http://realfavicongenerator.net/
      desktop:
        url: /images/logo.jpeg
        gravatar: false
      android:
        url: /images/logo.jpeg
        gravator: false
      apple:
        url: /images/apple-touch-icon.png
        gravator: false
    social_links:
        github: https://github.com/HelenZhangLP
    post_count: 5
    highlight: monokai

# keept it like this to add the root path (probably a bug)
root: ..

tag_generator:
  per_page: 10


solar:
    # factor between 0 (fast), 1(normal), 2(very slow)  
    speed: 1
    sun_image: /images/sun.png
    earth_image: /images/earth.png
    jupiter_image: /images/jupiter.png
    mars_image: /images/mars.png
    mercury_image: /images/mercury.png
    shadow_image: /images/shadow.png
    venus_image: /images/venus.png
    space_flight_image: /images/space_flight.jpeg

# RSS
rss: false

mermaid: ## mermaid url https://github.com/knsv/mermaid
  enable: true  # default true
  startOnload: true  #default true
  version: "7.1.2" # default v7.1.2
  options:  # find more api options from https://github.com/knsv/mermaid/blob/master/src/mermaidAPI.js

# Plugins
plugins:
    disqus_shortname: # Disqus Comments Shortname
    google_analytics: # enter the tracking ID for your Google Analytics

# Miscellaneous
miscellaneous:
    open_graph: # see http://ogp.me
        fb_app_id:
        fb_admins:
        twitter_id:
        google_plus:

# pagination or paging
pagination:
  nav_prev_text: '<'
  nav_next_text: '>'
